### ISSUE TITLE
No coverage for 'Locations'

### ISSUE THREAD

**Issue by jwelker9** [uniQuk/CA-Terraform-json#1]
Hello,

First, I wanted to thank you for this tool. I'm rolling over to leveraging Terraform for Conditional Access and I've got a ton to convert. So this tool has already been very helpful. I've noticed though that this tool isn't converting anything related to **locations** or **devices**. I'm looking in to updating your code myself, but unfortunately I know very little python so I'm still working on it. But thought I'd share that with you.

Thanks again for the tool!

Example:

[Terraform - Locations and Devices:](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/conditional_access_policy#argument-reference)
   devices {
      filter {
        mode = "exclude"
        rule = "device.operatingSystem eq \"Doors\""
      }
    }

    locations {
      included_locations = ["All"]
      excluded_locations = ["AllTrusted"]
    }

**Comment by jshhrt** [comment]
@jwelker9 thanks for the comment. I'm glad you found it useful.

I've added a location and devices block to the python code so that it will output those now if they are in the json. 

While it's generating the device block if it exists I haven't fully tested it's validity in Terraform yet:

```
locations {
      included_locations = ["00000000-0000-0000-0000-000000000000"]
      excluded_locations = ["AllTrusted"]
    }

devices {
      filter {
        mode = "include"
        rule = "device.isCompliant -eq True -and device.displayName -startsWith \"DC01\""
      }
    }
  }
```

**Comment by jshhrt** [comment]
@jwelker9 added an initial PowerShell version of the script as well if that's easier to use. Generating valid Terraform from the MS test policies (noticed some formatting inconsistencies with line breaks on the uploaded version).

**Comment by jwelker9** [comment]
You rock! I will probably take that powershell version and run with it. I did end up adding locations and devices as well, but I got stuck on some of the other attributes I needed to copy over. Thanks again.
